sudo: false
dist: trusty
language: node_js
node_js: 8.12

cache:
  yarn: true
  directories:
    - node_modules

addons:
  firefox: latest
  chrome: stable

branches:
  only:
   - master

script:
  - npm install
  - npm run bootstrap
  - npm run lint
  - npm test
